services:
    nginx:
        build:
            context: .
            dockerfile_inline: |
                FROM nginx:1.25.1-alpine3.17-slim
                COPY default.conf /etc/nginx/conf.d/default.conf
        command: nginx -g "daemon off;"
        ports:
            - "${APP_PORT}:80"
        depends_on:
            - webserver
            - web
        restart: unless-stopped
        networks:
            - skynet
    webserver:
        build:
            context: /home/thefatpanda/Documents/devOps/personal/budgetbee-clean-test/api
            dockerfile: Dockerfile
        working_dir: /var/www/html
        command: sh entrypoint.sh
        environment:
            DB_HOST: mysql
            DB_DATABASE: ${DB_DATABASE}
            DB_USERNAME: ${DB_USERNAME}
            DB_PASSWORD: ${DB_PASSWORD}
        depends_on:
            mysql:
                condition: service_healthy
        restart: unless-stopped
        networks:
            - skynet
    web:
        build:
            context: /home/thefatpanda/Documents/devOps/personal/budgetbee-clean-test/web
            dockerfile: Dockerfile
        restart: unless-stopped
        networks:
            - skynet
    mysql:
        build:
            context: .
            dockerfile_inline: |
                FROM mysql:latest
        ports:
            - "${DB_PORT:-3306}:3306"
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        healthcheck:
            test: ["CMD-SHELL", "mysqladmin ping -h localhost --silent"]
            timeout: 20s
            retries: 100
        restart: unless-stopped
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - skynet
networks:
    skynet:
volumes:
    db_data:
